### ISSUE TITLE
Pull Data from Shelter Manager

### ISSUE THREAD

**Issue by GeorgesGITHUB** [Team-27-Capstone/Catstone#66]
### Description:
- Gets and stores the report, using shelter manager's API, as a JSON file.
- Addresses requirements https://github.com/Team-27-Capstone/Catstone/issues/47 and https://github.com/Team-27-Capstone/Catstone/issues/59

### Assumption:
- The report has up to date information

### Command:
`importShelterManagerReport(  )
`
### Pre-condition(s):
- None

### Post-condition(s):
- Returns a JSON file representing data from the most recent report

**Comment by NicholasMorinUO** [comment]
The daily CRON job should accomplish this, in the meantime I'll throw a JSON in the GitHub to start working on the other parts of the data pipeline.

**Comment by GeorgesGITHUB** [comment]
Description isn't accurate, post-condition is
